name: Java CI

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install OpenJDK 11
      run: sudo apt-get install openjdk-11-jdk -y

    - name: Check Java version
      run: java -version

    - name: Install Maven
      run: sudo apt-get install maven -y

    - name: Download dependencies
      run: mvn dependency:resolve

    - name: Build project
      run: mvn clean package --file pom.xml

    - name: Run unit tests
      run: mvn test

    - name: Update project code
      run: |
        git config --global user.name 'Your Name'
        git config --global user.email 'your-email@example.com'
        git add .
        git commit -m "Update project"
        git push
