name: Java CI

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Install OpenJDK 17
      run: sudo apt-get install openjdk-17-jdk openjdk-17-jre -y

    - name: Check Java version
      run: java -version
      
    - name: Go to project directory
      run: cd cicd
      working-directory: $GITHUB_WORKSPACE
      
    - name: ls this
      run: | 
        ls -al
        pwd
        ls -al /      

    - name: chmod file
      run: chmod +x mvnw
      
    - name: Build project
      run: ./mvnw clean package

    - name: Run it
      run: java -jar target/*.jar --server.port=8080

    - name: Update project code
      run: |
        git config --global user.name 'Your Name'
        git config --global user.email 'your-email@example.com'
        git add .
        git commit -m "Update project"
        git push
