name: Java CI

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Install OpenJDK 17
      uses: actions/setup-java@v4
      with:
        distribution: 'zulu'
        java-version: '17'
        
    - name: Checkout code
      uses: actions/checkout@v3      
    
    - name: Check Java version
      run: java -version
        
    - name: install dependencies
      run: mvn compile
      
    - name: make package
      run: mvn package -DskipTests

    - name: Testing
      run: mvn test

    - name: Update project code
      run: |
        git config --global user.name 'Your Name'
        git config --global user.email 'your-email@example.com'
        git add .
        git commit -m "Update project"
        git push
