name: Java CI

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
          java-version: '17'
          distribution: 'adopt'
    - name: Check Java version
      run: |
        export JAVA_HOME=/usr/lib/jvm/adoptopenjdk-17-hotspot-amd64
        $JAVA_HOME/bin/java -version
        
    - name: chmod file
      run: chmod +x ./mvnw
      
    - name: Build project
      run: ./mvnw clean package

    - name: Run it
      run: java -jar ./target/*.jar --server.port=8080

    - name: Update project code
      run: |
        git config --global user.name 'Your Name'
        git config --global user.email 'your-email@example.com'
        git add .
        git commit -m "Update project"
        git push
