name: Java CI

on:
  push:
    branches:
      - main
  workflow_dispatch:
  pull_request:
    types: [opened, synchronize]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Install OpenJDK 17
      uses: actions/setup-java@v4
      with:
        distribution: 'zulu'
        java-version: '17'
        
    - name: Checkout code
      uses: actions/checkout@v3      
    
    - name: Check Java version
      run: java -version
        
    - name: install dependencies
      run: mvn compile
      
    - name: make package
      run: mvn package -DskipTests

    - name: Create new branch
      run: git checkout -b second-branch

    - name: Commit and push changes
      run: |
        git add .
        git commit -m "Update code for pull request"
        git push origin second-branch

    - name: Create pull request
      uses: peter-evans/create-pull-request@v3
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        branch: second-branch
        title: "Update code for pull request"
        body: |
          Code has been changed.

    - name: Testing
      run: mvn test
